name: Run Python Scripts Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight UTC

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      - name: Run Info Agent
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python info_agent.py

      - name: Run BTC Agent
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: python btc_agent.py

      - name: Run Email Agent
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python email_agent.py


